server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/course
    username: root
    password: wym990323
    driver-class-name: com.mysql.cj.jdbc.Driver
#    # druid data source
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20

## mybatis settings
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.entity

#pagehelper settings
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql